dist: trusty

language: java

jdk:
  - oraclejdk8

matrix:
  include:
  - os: linux
    env: CUSTOM_JDK="oraclejdk8"

before_install:
  - env
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then jdk_switcher use "$CUSTOM_JDK"; fi`

script:
  - travis_retry mvn clean package

after_success:
  - mvn clean

notifications:
  email:
    recipients:
      - chpei@foxmail.com
  on_success: always
  on_failure: always

