dist: trusty

language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "$SONAR_ORG"
    token:
      secure: "$SONAR_TOKEN"

matrix:
  include:
  - os: linux
    env: CUSTOM_JDK="oraclejdk8"

before_install:
  - env
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then jdk_switcher use "$CUSTOM_JDK"; fi

script:
  - travis_retry mvn clean
  - travis_retry mvn package jacoco:report coveralls:report
  - travis_retry mvn sonar:sonar

after_success:
  - java -jar target/locksbenchmark-1.0.jar -r 1 -w 1
  - java -jar target/locksbenchmark-1.0.jar -r 1 -w 5
  - java -jar target/locksbenchmark-1.0.jar -r 5 -w 1
  - mvn clean

notifications:
  email:
    recipients:
      - chpei@foxmail.com
  on_success: change
  on_failure: always

