language: java

jdk:
  - oraclejdk8

script:
  - travis_retry mvn clean package

after_success:
  - mvn clean

notifications:
  email:
    recipients:
      - chpei@foxmail.com
  on_success: always
  on_failure: always

