dist: trusty

language: java

jdk:
  - oraclejdk8

matrix:
  include:
  - os: linux
    env: CUSTOM_JDK="oraclejdk8"

before_install:
  - env
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then jdk_switcher use "$CUSTOM_JDK"; fi

script:
  - travis_retry mvn clean package

after_success:
  - java -jar target/locksbenchmark-1.0.jar -r 1 -w 1
  - java -jar target/locksbenchmark-1.0.jar -r 1 -w 5
  - java -jar target/locksbenchmark-1.0.jar -r 5 -w 1
  - java -jar target/locksbenchmark-1.0.jar -r 5 -w 5
  - java -jar target/locksbenchmark-1.0.jar -r 1 -w 20
  - java -jar target/locksbenchmark-1.0.jar -r 20 -w 1
  - java -jar target/locksbenchmark-1.0.jar -r 20 -w 20
  - mvn clean

notifications:
  email:
    recipients:
      - chpei@foxmail.com
  on_success: change
  on_failure: always

